site_name: Silvia Alvarado
nav:
  - Biography: index.md
  - Education, Experience, and Skills: edu_exp.md
  - Past Work: pastwork.md

theme:
  name: material
  logo: images/wizeline.png
  extra_css:
    -css/extra.css