site_name: Silvia Alvarado
nav:
  - Home: index.md
  - Education and Experience: edu_exp.md
  - Past Work: pastwork.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png