site_name: Silvia Alvarado
nav:
  - Biography: index.md
  - Education, Experience, and Skills: edu_exp.md
  - Past Work: pastwork.md

theme:
  name: material
  palette:
    primary: black
    accent: indigo
  logo: images/wizeline_isotype.png